### PR TITLE
Removed note about Flex

### PR DESCRIPTION
**Pull request by Nyholm**
Every package is compatible with Flex. However, you mean that you dont have a recipe. 

I think this package is an excellent candidate for a recipe. We should add something like this to a recipe to make the bundle installable: 

```
trikoder_oauth2:
  authorization_server:
    private_key: /var/oauth/private.key # Change this
    encryption_key: 'foobar' # Change this
  resource_server:
    public_key: /var/oauth/public.key # Change this
  persistence:
    doctrine: ~
```

If you submit a recipe to https://github.com/symfony/recipes-contrib I would be happy to approve it.

### CODE REVIEW

**Comment by spideyfusion** [comment]
@Nyholm @Allypost created a pull request for the Symfony recipe, but for some reason the build fails on PHP 7.4: https://github.com/symfony/recipes-contrib/pull/728

**Comment by Nyholm** [comment]
Hm. Master is red in symfony/recipes-contrib. I'll check.

**Comment by Nyholm** [comment]
The recipe is merged. 

Thank you @Allypost

**Comment by spideyfusion** [comment]
Glad to finally have this PR resolved, thanks @Nyholm! :smile:

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
