### PR TITLE
Symfony 5

### PR DESCRIPTION
**Pull request by elchris**
- I had to reduce travis.yml to php 7.2 and 7.3 with xdebug 2.7.2
- - with this said it should work with 7.4 with proper build
- I have done **no** manual testing
- I've only focused on making the tests pass
- This branch contains everything from **2.x** and **master** branches
- - Including the work that had already been done in **master** to upgrade to league 8
- It has symfony 5 with the latest possible version of every package that was in 2.x
- - league 8
- - I also added a reference to "roave/security-advisories": "dev-master"
- - I anchored it to symfony 5.0.2
- - I disabled support for zendframework/diactoros in favor of nyholm/psr-7 in TestKernel.php::configurePsrHttpFactory which was probably a less than optimal idea
- I have tested against PHP 7.2.26 (cli) (built: Dec 19 2019 02:10:39) ( NTS )
- - **The tests pass**
- I have tested against PHP 7.4.1 (cli) (built: Dec 18 2019 14:47:11) ( NTS )
- - Zend Engine v3.4.0, Copyright (c) Zend Technologies
- - with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
- - with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies
- - **The tests pass**
- Deprecation Notices:
- - 1 Direct
- - 8 Indirect

### CODE REVIEW

**Comment by elchris** [comment]
I'll try to add some more test coverage over the weekend.

**Comment by X-Coder264** [comment]
Thank you for the PR, but we don't plan to merge it. It drops support for Symfony 3.4 and 4.x on v2.x which is unacceptable. There are also a bunch of other changes here unrelated to updating the bundle to Symfony 5 like the removal of the testing in CI of the bundle with `zendframework/diactoros` which we support on purpose.

The work to bring Symfony 5 support to the bundle has already started via https://github.com/trikoder/oauth2-bundle/pull/118 and it targets the master branch (future v3.x major release) because it drops support for Symfony 3.4 due to some breaking changes.

**Comment by elchris** [comment]
Yea sorry about that, I realized after I went to bed last night that I should not have picked v2.x for this pull request, I really meant to pick a different branch, because of course we really didn't want it in v2.x. I didn't know the work had already started elsewhere.

**Comment by X-Coder264** [comment]
No problem, thanks for the effort.

**Pull request closed without merging**
