### PR TITLE
Update TrikoderOAuth2Extension.php

### PR DESCRIPTION
**Pull request by vuryss**
Fixes https://github.com/trikoder/oauth2-bundle/issues/279

### CODE REVIEW

**Comment by DanielSchmidDS** [comment]
Yes. This change fixes my problem in Symfony 5.3.
Thanks.

**Comment by HypeMC** [comment]
@vuryss Unfortunately this would revert https://github.com/trikoder/oauth2-bundle/pull/12 . The solution would need to work on all versions of Doctrine Bundle supported by this bundle without reintroducing old bugs.

**Comment by vuryss** [comment]
@HypeMC which is the bug that #12 solves?

**Comment by HypeMC** [comment]
@vuryss If I remember correctly, without the fix, doctrine bundle would create a "default" connection if one didn't exist which would be a problem if your `default_connection` is named differently.

**Comment by vuryss** [comment]
> @vuryss If I remember correctly, without the fix, doctrine bundle would create a "default" connection if one didn't exist which would be a problem if your `default_connection` is named differently.

This sounds like doctrine bug, not something that should be fixed with this bundle tho...

Anyway do you have a better idea how to fix that and not be stuck with the old bundle version?
I want to start using the attributes that the new doctrine bundle version provides :)

**Comment by HypeMC** [comment]
@vuryss This seems to have been fixed in newer versions https://github.com/doctrine/DoctrineBundle/pull/1356 . I would need to look into it more to give you any concrete answers.

**Comment by vuryss** [comment]
> @vuryss This seems to have been fixed in newer versions [doctrine/DoctrineBundle#1356](https://github.com/doctrine/DoctrineBundle/pull/1356) . I would need to look into it more to give you any concrete answers.

That is the very commit that is causing the oauth2 bundle to break, having that extra connection configuration.

**Comment by HypeMC** [comment]
@vuryss This might get fixed on Doctrine's side https://github.com/doctrine/DoctrineBundle/issues/1366

**Comment by vuryss** [comment]
Yes a lot of discussion is taking place at doctrine bundle side. I guess this is not the only side effect of the last changes.
Linking: 
https://github.com/doctrine/DoctrineBundle/pull/1368
https://github.com/doctrine/DoctrineBundle/issues/1362

I hope it's resolved soon.

**Comment by vuryss** [comment]
I can confirm https://github.com/doctrine/DoctrineBundle/pull/1368 fixes this issue, if it's merged and released I will close this one.
Basically it reverts the problematic https://github.com/doctrine/DoctrineBundle/pull/1356

**Comment by vuryss** [comment]
Fixed in doctrine bundle 2.4.2

**Pull request closed without merging**
