### PR TITLE
Added interfaces for converters

### LINKED ISSUE #76: [Easy pick] All final classes must have an interface
We need this to be able to mock and tests our code.

### PR DESCRIPTION
**Pull request by Nyholm**
Related to #76

After #82 and this PR is merged we can close #76

### CODE REVIEW

**Comment by spideyfusion** [comment]
@Nyholm Please resolve the conflicting file so we can merge this in! 👍

**Comment by Nyholm** [comment]
Thank you. I've rebased the PR

**Comment by spideyfusion** [comment]
@Nyholm We got hit by https://github.com/symfony/symfony/issues/32879. I'll push more strict version requirements for PHPUnit on `master` until Symfony releases a new patch version.

**Comment by spideyfusion** [comment]
Thank you for your continued contributions @Nyholm!

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
