### PR TITLE
Add possibility to disable access token saving

### PR DESCRIPTION
**Pull request by Orkin**
@X-Coder264 this is a WIP PR just to know if this is the right way

### CODE REVIEW

**Comment by Orkin** [comment]
@X-Coder264 @HypeMC Any news here ?

**Comment by X-Coder264** [comment]
@Orkin We plan on releasing 3.2 this week and then we'll take a look at this PR.

**Comment by HypeMC** [comment]
@Orkin Hi, are you still interested in finishing this one? If yes, please rebase cause there seem to be some conflicting files & the commit history is a mess.

**Comment by Orkin** [comment]
No 8 months after I forked it and did it on my own sorry

**Comment by HypeMC** [comment]
@Orkin In any case thank you, feel free to reopen.

**Pull request closed without merging**
