### PR TITLE
Symfony 5.0

### PR DESCRIPTION
**Pull request by rbaarsma**
Adds Symfony 5 support and bumps minimum symfony version to 4.4 (as of January symfony 4.3 is no longer actively maintained, only security fixes and in the master of this bundle I opt to keep up with the times. If anyone uses an older version they will automatically use an older version of this bundle)

### CODE REVIEW

**Comment by rbaarsma** [comment]
@X-Coder264 not 100% sure if I should be merging this into v2.x branch or master

**Comment by X-Coder264** [comment]
@rbaarsma Please target this to master.

**Comment by rbaarsma** [comment]
@X-Coder264 hmm that adds a bunch of things from v2.x that are apparently not in master? Any chance v2.x should be merged into master? Or should I re-do my changes on the master branch..?

**Comment by X-Coder264** [comment]
We will merge v2.x into master soon (probably we will wait to merge the PHP 7.4 PRs into 2.x though).

**Comment by rbaarsma** [comment]
@X-Coder264 I took a look at the travis errors and tested locally. I've fixed some symfony-related errors and had to bump the php-cs-fixer version to test symfony 5. There's a bunch of failures left that seem to have no direct relation to the update, but obviously they might be. I think I'll wait for the v2.x branch te be merged into master, before further diving into this, because I think it's unstable at this point and don't want to do work someone else is already doing.

**Comment by X-Coder264** [comment]
@rbaarsma Sorry for the delay. v2.x branch was just merged into master so if you rebase your branch with master now there shouldn't be any blockers left in order to complete this PR.

**Comment by rbaarsma** [comment]
I've rebased this on master, but still many tests are failing. I don't have time right now to look into it. 

If https://github.com/trikoder/oauth2-bundle/pull/150 is fully fixed and ok, it's fine by me if you merge that instead and close this. 

Otherwise maybe next week I'll have time to look at the tests

**Comment by X-Coder264** [comment]
@rbaarsma Thank you for your effort. #150 just got merged into master.

**Pull request closed without merging**
