### PR TITLE
Add support for the "implicit" grant type

### LINKED ISSUE #1: Add support for the "implicit" grant type

### PR DESCRIPTION
**Pull request by ajgarlag**
Fixes #1 

Includes commits from #18. I'll rebase once #18 is merged.

### CODE REVIEW

**Comment by ajgarlag** [comment]
Rebased and ready for review

**Comment by X-Coder264** [comment]
Thank you @ajgarlag for the PR.

We'll be tagging 2.0 next week and in the meantime we'll be focusing on writing some documentation. If you could send in some PR that documents this (something like https://github.com/trikoder/oauth2-bundle/blob/master/docs/password-grant-handling.md ) and #18 that would be highly appreciated.

**Comment by ajgarlag** [comment]
@X-Coder264 Thanks for merging.

I'm very busy these days, so I won't be able to send the documentation PR this week. Sorry.

**Comment by X-Coder264** [comment]
No problem @ajgarlag. Thanks for the PR. We'll work on documenting the grants ourselves before tagging the new release.

**Pull request merged**
